// VerseClass VerseExperimental.$SolarisSignatureFunctionOuter
// Size: 0x28 (Inherited: 0x28)
struct U$SolarisSignatureFunctionOuter : UObject {
};

// VerseClass VerseExperimental.date_time_ticks
// Size: 0x70 (Inherited: 0x28)
struct Udate_time_ticks : UObject {
	int64_t __verse_0x8DE5F121_NanosecondsPerTick; // 0x28(0x08)
	int64_t __verse_0x358147B9_TicksPerDay; // 0x30(0x08)
	int64_t __verse_0x5C0949D3_TicksPerHour; // 0x38(0x08)
	int64_t __verse_0x59DFB831_TicksPerMicrosecond; // 0x40(0x08)
	int64_t __verse_0xD20E16AF_TicksPerMillisecond; // 0x48(0x08)
	int64_t __verse_0x4420B794_TicksPerMinute; // 0x50(0x08)
	int64_t __verse_0x3E0178E0_TicksPerSecond; // 0x58(0x08)
	int64_t __verse_0xA7911900_TicksPerWeek; // 0x60(0x08)
	int64_t __verse_0xE371C089_TicksPerYear; // 0x68(0x08)

	void $InitCDO(); // Function VerseExperimental.date_time_ticks.$InitCDO // (None) // @ game+0xda05cc
};

// VerseClass VerseExperimental.VerseExperimental
// Size: 0x28 (Inherited: 0x28)
struct UVerseExperimental : UObject {

	struct Ftime_span _L_2fVerse_2eorg_2fVerseExperimental_N_Roperator_27_2f_27_L_Ntime__span_M_Nfloat_R(struct Ftuple_Ltime__span_Mfloat_R __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_Roperator_27_2f_27_L_Ntime__span_M_Nfloat_R // (Final|Static|Public|HasOutParms|HasDefaults|BlueprintCallable) // @ game+0xda05cc
	struct Ftime_span _L_2fVerse_2eorg_2fVerseExperimental_N_Roperator_27_2d_27_L_Ndate__time_M_Ndate__time_R(struct Ftuple_Ldate__time_Mdate__time_R __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_Roperator_27_2d_27_L_Ndate__time_M_Ndate__time_R // (Final|Static|Public|HasOutParms|HasDefaults|BlueprintCallable) // @ game+0xda05cc
	struct Fdate_time _L_2fVerse_2eorg_2fVerseExperimental_N_Roperator_27_2d_27_L_Ndate__time_M_Ntime__span_R(struct Ftuple_Ldate__time_Mtime__span_R __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_Roperator_27_2d_27_L_Ndate__time_M_Ntime__span_R // (Final|Static|Public|HasOutParms|HasDefaults|BlueprintCallable) // @ game+0xda05cc
	struct Ftime_span _L_2fVerse_2eorg_2fVerseExperimental_N_Roperator_27_2d_27_L_Ntime__span_R(struct Ftime_span __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_Roperator_27_2d_27_L_Ntime__span_R // (Final|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xda05cc
	struct Ftime_span _L_2fVerse_2eorg_2fVerseExperimental_N_Roperator_27_2d_27_L_Ntime__span_M_Ntime__span_R(struct Ftuple_Ltime__span_Mtime__span_R __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_Roperator_27_2d_27_L_Ntime__span_M_Ntime__span_R // (Final|Static|Public|HasOutParms|HasDefaults|BlueprintCallable) // @ game+0xda05cc
	struct Fdate_time _L_2fVerse_2eorg_2fVerseExperimental_N_Roperator_27_2b_27_L_Ndate__time_M_Ntime__span_R(struct Ftuple_Ldate__time_Mtime__span_R __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_Roperator_27_2b_27_L_Ndate__time_M_Ntime__span_R // (Final|Static|Public|HasOutParms|HasDefaults|BlueprintCallable) // @ game+0xda05cc
	struct Ftime_span _L_2fVerse_2eorg_2fVerseExperimental_N_Roperator_27_2b_27_L_Ntime__span_M_Ntime__span_R(struct Ftuple_Ltime__span_Mtime__span_R __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_Roperator_27_2b_27_L_Ntime__span_M_Ntime__span_R // (Final|Static|Public|HasOutParms|HasDefaults|BlueprintCallable) // @ game+0xda05cc
	struct Ftime_span _L_2fVerse_2eorg_2fVerseExperimental_N_Roperator_27_2a_27_L_Ntime__span_M_Nfloat_R(struct Ftuple_Ltime__span_Mfloat_R __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_Roperator_27_2a_27_L_Ntime__span_M_Nfloat_R // (Final|Static|Public|HasOutParms|HasDefaults|BlueprintCallable) // @ game+0xda05cc
	struct Ftime_span _L_2fVerse_2eorg_2fVerseExperimental_N_Roperator_27_2a_27_L_Nfloat_M_Ntime__span_R(struct Ftuple_Lfloat_Mtime__span_R __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_Roperator_27_2a_27_L_Nfloat_M_Ntime__span_R // (Final|Static|Public|HasOutParms|HasDefaults|BlueprintCallable) // @ game+0xda05cc
	char _L_2fVerse_2eorg_2fVerseExperimental_N_RValidateDateTime_L_Nint_M_Nint_M_Nint_M_Nint_M_Nint_M_Nint_M_Nint_R(struct Ftuple_Lint_Mint_Mint_Mint_Mint_Mint_Mint_R __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RValidateDateTime_L_Nint_M_Nint_M_Nint_M_Nint_M_Nint_M_Nint_M_Nint_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x63d2f04
	OptionProperty _L_2fVerse_2eorg_2fVerseExperimental_N_RValidate_L_Ndate__time_R(struct Fdate_time __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RValidate_L_Ndate__time_R // (Final|Static|Public|HasOutParms|HasDefaults|BlueprintCallable) // @ game+0xda05cc
	struct Fdate_time _L_2fVerse_2eorg_2fVerseExperimental_N_RUtcNow(struct Ftuple_L_R __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RUtcNow // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x63d2efc
	VerseStringProperty _L_2fVerse_2eorg_2fVerseExperimental_N_RToString_L_Ntime__span_R(struct Ftime_span __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RToString_L_Ntime__span_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x63d2ef4
	VerseStringProperty _L_2fVerse_2eorg_2fVerseExperimental_N_RToString_L_Ndate__time_R(struct Fdate_time __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RToString_L_Ndate__time_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x63d2eec
	struct Ftime_span _L_2fVerse_2eorg_2fVerseExperimental_N_RPerformNativeSubtract_L_Ntime__span_M_Ntime__span_R(struct Ftuple_Ltime__span_Mtime__span_R __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RPerformNativeSubtract_L_Ntime__span_M_Ntime__span_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x63d2ee4
	struct Ftime_span _L_2fVerse_2eorg_2fVerseExperimental_N_RPerformNativeSubtract_L_Ndate__time_M_Ndate__time_R(struct Ftuple_Ldate__time_Mdate__time_R __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RPerformNativeSubtract_L_Ndate__time_M_Ndate__time_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x63d2ed4
	struct Fdate_time _L_2fVerse_2eorg_2fVerseExperimental_N_RPerformNativeSubtract_L_Ndate__time_M_Ntime__span_R(struct Ftuple_Ldate__time_Mtime__span_R __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RPerformNativeSubtract_L_Ndate__time_M_Ntime__span_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x63d2edc
	struct Ftime_span _L_2fVerse_2eorg_2fVerseExperimental_N_RPerformNativeNegate_L_Ntime__span_R(struct Ftime_span __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RPerformNativeNegate_L_Ntime__span_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x63d2ecc
	struct Ftime_span _L_2fVerse_2eorg_2fVerseExperimental_N_RPerformNativeMultiply_L_Ntime__span_M_Nfloat_R(struct Ftuple_Ltime__span_Mfloat_R __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RPerformNativeMultiply_L_Ntime__span_M_Nfloat_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x63d2ec4
	struct Ftime_span _L_2fVerse_2eorg_2fVerseExperimental_N_RPerformNativeDivide_L_Ntime__span_M_Nfloat_R(struct Ftuple_Ltime__span_Mfloat_R __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RPerformNativeDivide_L_Ntime__span_M_Nfloat_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x63d2ebc
	struct Ftime_span _L_2fVerse_2eorg_2fVerseExperimental_N_RPerformNativeAdd_L_Ntime__span_M_Ntime__span_R(struct Ftuple_Ltime__span_Mtime__span_R __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RPerformNativeAdd_L_Ntime__span_M_Ntime__span_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x63d2eb4
	struct Fdate_time _L_2fVerse_2eorg_2fVerseExperimental_N_RPerformNativeAdd_L_Ndate__time_M_Ntime__span_R(struct Ftuple_Ldate__time_Mtime__span_R __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RPerformNativeAdd_L_Ndate__time_M_Ntime__span_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x63d2eac
	OptionProperty _L_2fVerse_2eorg_2fVerseExperimental_N_RLessEqual_L_Ndate__time_M_Ndate__time_R(struct Ftuple_Ldate__time_Mdate__time_R __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RLessEqual_L_Ndate__time_M_Ndate__time_R // (Final|Static|Public|HasOutParms|HasDefaults|BlueprintCallable) // @ game+0xda05cc
	OptionProperty _L_2fVerse_2eorg_2fVerseExperimental_N_RLessEqual_L_Ntime__span_M_Ntime__span_R(struct Ftuple_Ltime__span_Mtime__span_R __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RLessEqual_L_Ntime__span_M_Ntime__span_R // (Final|Static|Public|HasOutParms|HasDefaults|BlueprintCallable) // @ game+0xda05cc
	OptionProperty _L_2fVerse_2eorg_2fVerseExperimental_N_RLess_L_Ndate__time_M_Ndate__time_R(struct Ftuple_Ldate__time_Mdate__time_R __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RLess_L_Ndate__time_M_Ndate__time_R // (Final|Static|Public|HasOutParms|HasDefaults|BlueprintCallable) // @ game+0xda05cc
	OptionProperty _L_2fVerse_2eorg_2fVerseExperimental_N_RLess_L_Ntime__span_M_Ntime__span_R(struct Ftuple_Ltime__span_Mtime__span_R __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RLess_L_Ntime__span_M_Ntime__span_R // (Final|Static|Public|HasOutParms|HasDefaults|BlueprintCallable) // @ game+0xda05cc
	OptionProperty _L_2fVerse_2eorg_2fVerseExperimental_N_RGreaterEqual_L_Ndate__time_M_Ndate__time_R(struct Ftuple_Ldate__time_Mdate__time_R __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RGreaterEqual_L_Ndate__time_M_Ndate__time_R // (Final|Static|Public|HasOutParms|HasDefaults|BlueprintCallable) // @ game+0xda05cc
	OptionProperty _L_2fVerse_2eorg_2fVerseExperimental_N_RGreaterEqual_L_Ntime__span_M_Ntime__span_R(struct Ftuple_Ltime__span_Mtime__span_R __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RGreaterEqual_L_Ntime__span_M_Ntime__span_R // (Final|Static|Public|HasOutParms|HasDefaults|BlueprintCallable) // @ game+0xda05cc
	OptionProperty _L_2fVerse_2eorg_2fVerseExperimental_N_RGreater_L_Ntime__span_M_Ntime__span_R(struct Ftuple_Ltime__span_Mtime__span_R __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RGreater_L_Ntime__span_M_Ntime__span_R // (Final|Static|Public|HasOutParms|HasDefaults|BlueprintCallable) // @ game+0xda05cc
	OptionProperty _L_2fVerse_2eorg_2fVerseExperimental_N_RGreater_L_Ndate__time_M_Ndate__time_R(struct Ftuple_Ldate__time_Mdate__time_R __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RGreater_L_Ndate__time_M_Ndate__time_R // (Final|Static|Public|HasOutParms|HasDefaults|BlueprintCallable) // @ game+0xda05cc
	int64_t _L_2fVerse_2eorg_2fVerseExperimental_N_RGetYear_L_Ndate__time_R(struct Fdate_time __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RGetYear_L_Ndate__time_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x63d2ea4
	int64_t _L_2fVerse_2eorg_2fVerseExperimental_N_RGetTotalSeconds_L_Ntime__span_R(struct Ftime_span __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RGetTotalSeconds_L_Ntime__span_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x63d2e9c
	int64_t _L_2fVerse_2eorg_2fVerseExperimental_N_RGetTotalMinutes_L_Ntime__span_R(struct Ftime_span __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RGetTotalMinutes_L_Ntime__span_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x63d2e94
	int64_t _L_2fVerse_2eorg_2fVerseExperimental_N_RGetTotalMilliseconds_L_Ntime__span_R(struct Ftime_span __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RGetTotalMilliseconds_L_Ntime__span_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x63d2e8c
	int64_t _L_2fVerse_2eorg_2fVerseExperimental_N_RGetTotalMicroseconds_L_Ntime__span_R(struct Ftime_span __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RGetTotalMicroseconds_L_Ntime__span_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x63d2e84
	int64_t _L_2fVerse_2eorg_2fVerseExperimental_N_RGetTotalHours_L_Ntime__span_R(struct Ftime_span __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RGetTotalHours_L_Ntime__span_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x63d2e7c
	int64_t _L_2fVerse_2eorg_2fVerseExperimental_N_RGetTotalDays_L_Ntime__span_R(struct Ftime_span __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RGetTotalDays_L_Ntime__span_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x63d2e74
	struct Ftime_of_day_parts _L_2fVerse_2eorg_2fVerseExperimental_N_RGetTimeOfDay_L_Ndate__time_R(struct Fdate_time __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RGetTimeOfDay_L_Ndate__time_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x63d2e6c
	int64_t _L_2fVerse_2eorg_2fVerseExperimental_N_RGetSeconds_L_Ntime__span_R(struct Ftime_span __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RGetSeconds_L_Ntime__span_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x63d2e64
	int64_t _L_2fVerse_2eorg_2fVerseExperimental_N_RGetSeconds_L_Ndate__time_R(struct Fdate_time __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RGetSeconds_L_Ndate__time_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x63d2e5c
	int64_t _L_2fVerse_2eorg_2fVerseExperimental_N_RGetNanoseconds_L_Ndate__time_R(struct Fdate_time __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RGetNanoseconds_L_Ndate__time_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x63d2e4c
	int64_t _L_2fVerse_2eorg_2fVerseExperimental_N_RGetNanoseconds_L_Ntime__span_R(struct Ftime_span __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RGetNanoseconds_L_Ntime__span_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x63d2e54
	enum class month_of_year _L_2fVerse_2eorg_2fVerseExperimental_N_RGetMonthOfYear_L_Ndate__time_R(struct Fdate_time __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RGetMonthOfYear_L_Ndate__time_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x63d2e3c
	int64_t _L_2fVerse_2eorg_2fVerseExperimental_N_RGetMonth_L_Ndate__time_R(struct Fdate_time __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RGetMonth_L_Ndate__time_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x63d2e44
	int64_t _L_2fVerse_2eorg_2fVerseExperimental_N_RGetMinutes_L_Ntime__span_R(struct Ftime_span __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RGetMinutes_L_Ntime__span_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x63d2e34
	int64_t _L_2fVerse_2eorg_2fVerseExperimental_N_RGetMinutes_L_Ndate__time_R(struct Fdate_time __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RGetMinutes_L_Ndate__time_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x63d2e2c
	int64_t _L_2fVerse_2eorg_2fVerseExperimental_N_RGetMilliseconds_L_Ntime__span_R(struct Ftime_span __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RGetMilliseconds_L_Ntime__span_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x63d2e24
	int64_t _L_2fVerse_2eorg_2fVerseExperimental_N_RGetMilliseconds_L_Ndate__time_R(struct Fdate_time __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RGetMilliseconds_L_Ndate__time_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x63d2e1c
	int64_t _L_2fVerse_2eorg_2fVerseExperimental_N_RGetMicroseconds_L_Ntime__span_R(struct Ftime_span __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RGetMicroseconds_L_Ntime__span_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x63d2e14
	int64_t _L_2fVerse_2eorg_2fVerseExperimental_N_RGetMicroseconds_L_Ndate__time_R(struct Fdate_time __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RGetMicroseconds_L_Ndate__time_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x63d2e0c
	int64_t _L_2fVerse_2eorg_2fVerseExperimental_N_RGetHours_L_Ntime__span_R(struct Ftime_span __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RGetHours_L_Ntime__span_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x63d2e04
	int64_t _L_2fVerse_2eorg_2fVerseExperimental_N_RGetHours_L_Ndate__time_R(struct Fdate_time __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RGetHours_L_Ndate__time_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x63d2dfc
	int64_t _L_2fVerse_2eorg_2fVerseExperimental_N_RGetDays_L_Ntime__span_R(struct Ftime_span __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RGetDays_L_Ntime__span_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x63d2df4
	enum class day_of_week _L_2fVerse_2eorg_2fVerseExperimental_N_RGetDayOfWeek_L_Ndate__time_R(struct Fdate_time __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RGetDayOfWeek_L_Ndate__time_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x63d2de4
	int64_t _L_2fVerse_2eorg_2fVerseExperimental_N_RGetDay_L_Ndate__time_R(struct Fdate_time __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RGetDay_L_Ndate__time_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x63d2dec
	struct Fdate_parts _L_2fVerse_2eorg_2fVerseExperimental_N_RGetDate_L_Ndate__time_R(struct Fdate_time __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RGetDate_L_Ndate__time_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x63d2ddc
	int64_t _L_2fVerse_2eorg_2fVerseExperimental_N_RDaysInYear_L_Nint_R(int64_t __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RDaysInYear_L_Nint_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x63d2dd4
	int64_t _L_2fVerse_2eorg_2fVerseExperimental_N_RDaysInMonth_L_Nint_M_Nint_R(struct Ftuple_Lint_Mint_R __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RDaysInMonth_L_Nint_M_Nint_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x63d2dcc
	struct Fdate_time _L_2fVerse_2eorg_2fVerseExperimental_N_RDateTimeMin(struct Ftuple_L_R __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RDateTimeMin // (Final|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xda05cc
	struct Fdate_time _L_2fVerse_2eorg_2fVerseExperimental_N_RDateTimeMax(struct Ftuple_L_R __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RDateTimeMax // (Final|Static|Public|HasOutParms|BlueprintCallable) // @ game+0xda05cc
	struct Ftime_span _L_2fVerse_2eorg_2fVerseExperimental_N_RCreateTimeSpan_L_Nint_M_Nint_M_Nint_M_Nint_M_Nint_R(struct Ftuple_Lint_Mint_Mint_Mint_Mint_R __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RCreateTimeSpan_L_Nint_M_Nint_M_Nint_M_Nint_M_Nint_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x63d2dc4
	OptionProperty _L_2fVerse_2eorg_2fVerseExperimental_N_RCreateDateTime_L_Nint_M_Nint_M_Nint_M_Nint_M_Nint_M_Nint_M_Nint_R(struct Ftuple_Lint_Mint_Mint_Mint_Mint_Mint_Mint_R __verse_0xB2CDDD72_Argument); // Function VerseExperimental.VerseExperimental._L_2fVerse_2eorg_2fVerseExperimental_N_RCreateDateTime_L_Nint_M_Nint_M_Nint_M_Nint_M_Nint_M_Nint_M_Nint_R // (Final|Native|Static|Public|HasOutParms|BlueprintCallable) // @ game+0x63d2dbc
	struct Ftime_span time_span$Factory(); // Function VerseExperimental.VerseExperimental.time_span$Factory // (Static|HasOutParms) // @ game+0xda05cc
	struct Ftime_of_day_parts time_of_day_parts$Factory(); // Function VerseExperimental.VerseExperimental.time_of_day_parts$Factory // (Static|HasOutParms) // @ game+0xda05cc
	struct Fdate_parts date_parts$Factory(); // Function VerseExperimental.VerseExperimental.date_parts$Factory // (Static|HasOutParms) // @ game+0xda05cc
	struct Fdate_time date_time$Factory(); // Function VerseExperimental.VerseExperimental.date_time$Factory // (Static|HasOutParms) // @ game+0xda05cc
	void $InitCDO(); // Function VerseExperimental.VerseExperimental.$InitCDO // (None) // @ game+0xda05cc
};

